### ISSUE TITLE
Assessing the fit with squared residuals

### ISSUE THREAD

**Issue by guillaumelenoir** [brandonckelly/carma_pack#11]
I have some doubts about the confidence levels for the fourth figure provided by the "assess_fit" function (in carma_pack.py and fig. 7 of the paper). Indeed, if the residuals follow of gaussian white noise, their squared values follow a chi squared, which is not what is indicated in the paper (section 3.4). So that I wonder about the validity of the confidence levels.

**Comment by brandonckelly** [comment]
Hi Guillaume,

If I understand your question correctly, you are thinking that the claim is
that the squared residuals follow Gaussian white noise? If so, that is not
correct. The squared residuals do indeed follow a chi-square distribution,
but that is not the point being made. Rather, the point is that the squared
residuals are a white noise sequence and thus should have an ACF consistent
with white noise. The distribution of the *ACF of the squared residuals* is
approximated as a Gaussian distribution in order to get confidence
intervals on the ACF (the ACF values of the squared residuals are not
chi-square distributed). This is the usual approximation based on the
central limit theorem.

Hope this helps,
Brandon

**Comment by guillaumelenoir** [comment]
Hi Brandon,
Thanks for the clear reply. I misunderstood the meaning of "white noise". Now that I have revised my theory and read again section 3.4 of your paper, I fully agree with the analysis.
